@HostAddress = https://localhost:7016

@JwtToken = your_jwt_token_from_login_or_register

@Rooms = api/rooms
@Users = api/users
@Songs = api/songs
@Spotify = api/spotify


#### ROOMS ####


GET {{HostAddress}}/{{Rooms}}
Authorization: Bearer {{JwtToken}}

###

@id=0
GET {{HostAddress}}/{{Rooms}}/{{id}}
Authorization: Bearer {{JwtToken}}

###

@slug=string
POST {{HostAddress}}/{{Rooms}}/slug/{{slug}}

###

POST {{HostAddress}}/{{Rooms}}
Content-Type: application/json
Authorization: Bearer {{JwtToken}}

{
  "Name": "My First Room"
  "IsActive": true,
  "Password": "securepassword"
  "PasswordConfirm": "securepassword"
}

###

PUT {{HostAddress}}/{{Rooms}}/{{id}}
Content-Type: application/json
Authorization: Bearer {{JwtToken}}

{
  "Name": "My First Room"
  "IsActive": true,
}

###

PUT {{HostAddress}}/{{Rooms}}/password/{{id}}
Content-Type: application/json
Authorization: Bearer {{JwtToken}}

{
  "Password": "newsecurepassword",
  "PasswordConfirm": "newsecurepassword"
}

###

DELETE {{HostAddress}}/{{Rooms}}/{{id}}
Authorization: Bearer {{JwtToken}}

###


#### USERS ####


GET {{HostAddress}}/{{Users}}

###

GET {{HostAddress}}/{{Users}}/me
Authorization: Bearer {{JwtToken}}

###

@id=0
GET {{HostAddress}}/{{Users}}/{{id}}

###

POST {{HostAddress}}/{{Users}}/login
Content-Type: application/json

{
  "Email": "anemail@email.com",
  "Password": "securepassword"
}

###

POST {{HostAddress}}/{{Users}}/register
Content-Type: application/json

{
  "Username": "myusername",
  "Email": "anemail@email.com",
  "Password": "securepassword",
  "PasswordConfirm": "securepassword"
}

###

PUT {{HostAddress}}/{{Users}}/me
Content-Type: application/json
Authorization: Bearer {{JwtToken}}

{
  "Username": "myusername",
  "Email": "anemail@email.com"
}

###

PUT {{HostAddress}}/{{Users}}/me/password
Content-Type: application/json
Authorization: Bearer {{JwtToken}}

{
  "Password": "securepassword",
  "PasswordConfirm": "securepassword"
}

###

POST {{HostAddress}}/{{Users}}/delete/me
Authorization: Bearer {{JwtToken}}

###


#### SONGS ####


@roomId=0
GET {{HostAddress}}/{{Songs}}/room/{{roomId}}
Authorization: Bearer {{JwtToken}}

###

@status=0
GET {{HostAddress}}/{{Songs}}/room/{{roomId}}/status/{{status}}
Authorization: Bearer {{JwtToken}}

###

@songId=string
POST {{HostAddress}}/{{Songs}}/room/{{roomId}}/{{songId}}

###


#### SPOTIFY ####


GET {{HostAddress}}/{{Spotify}}/token
Authorization: Bearer {{JwtToken}}

###

GET {{HostAddress}}/{{Spotify}}/oathlink

###

@q=string
@offset=0
@market=string
GET {{HostAddress}}/{{Spotify}}/search/{{q}}/{{offset}}/{{market}}

###

@roomId=0
@songId=0
POST {{HostAddress}}/{{Spotify}}/playlist/{{roomId}}/{{songId}}
Authorization: Bearer {{JwtToken}}

###